version: 0.2

env:
  parameter-store:
    ARTIFACTORY_SETTINGS: /ci/datasonnet/artifactorysettings

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo $ARTIFACTORY_SETTINGS > /root/.m2/settings.xml
      - |
        case "$CODEBUILD_WEBHOOK_HEAD_REF" in
          refs/heads/*) export VERSIONING_GIT_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/} ;;
          refs/tags/*) export VERSIONING_GIT_TAG=${CODEBUILD_WEBHOOK_HEAD_REF#refs/tags/} ;;
        esac
      - ./gradlew :version -q
      - ./gradlew -q test
      - ./gradlew -q buildPlugin
      - |
        case "$CODEBUILD_WEBHOOK_TRIGGER" in
          pr/*) echo "pull request, not uploaded" ;;
          *) aws s3 cp build/distributions/*.zip s3://datasonnet/intellij/ ;;
        esac

cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.gradle/**/*'